/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// (&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begreper/20b2e10d-9fe1-11e5-a9f8-e4115b280940&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
    /// </summary>
    [DataContract]
        public partial class AdresseFrittFormat
    {
       
        /// <summary>
        /// (&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begreper/20b2e0fb-9fe1-11e5-a9f8-e4115b280940&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
        /// </summary>
        /// <value>(&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begreper/20b2e0fb-9fe1-11e5-a9f8-e4115b280940&#x27;&gt;Begrepsreferanse&lt;/a&gt;)</value>
        [DataMember(Name="adressetekst", EmitDefaultValue=false)]
        public List<string> Adressetekst { get; set; }

        /// <summary>
        /// Gets or Sets Poststedsnavn
        /// </summary>
        [DataMember(Name="poststedsnavn", EmitDefaultValue=false)]
        public string Poststedsnavn { get; set; }

        /// <summary>
        /// Gets or Sets Postnummer
        /// </summary>
        [DataMember(Name="postnummer", EmitDefaultValue=false)]
        public string Postnummer { get; set; }

        /// <summary>
        /// Gets or Sets Landkode
        /// </summary>
        [DataMember(Name="landkode", EmitDefaultValue=false)]
        public string Landkode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
    }
}
