/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// oversikt over gjeld, tilgodebeløp og betalinger mellom deg og Skatteetaten
    /// </summary>
    [DataContract]
        public partial class AlleKrav :  IEquatable<AlleKrav>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlleKrav" /> class.
        /// </summary>
        /// <param name="partIdentifikator">partIdentifikator (required).</param>
        /// <param name="periode">periode (required).</param>
        /// <param name="krav">Vanligvis en debettransaksjon i reskontro, som kjennetegnes av at den skal betales av en debitor. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c63129-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;).</param>
        /// <param name="skjermet">skjermet (required).</param>
        public AlleKrav(string partIdentifikator = default(string), Periode periode = default(Periode), List<Krav> krav = default(List<Krav>), bool? skjermet = default(bool?))
        {
            // to ensure "partIdentifikator" is required (not null)
            if (partIdentifikator == null)
            {
                throw new InvalidDataException("partIdentifikator is a required property for AlleKrav and cannot be null");
            }
            else
            {
                this.PartIdentifikator = partIdentifikator;
            }
            // to ensure "periode" is required (not null)
            if (periode == null)
            {
                throw new InvalidDataException("periode is a required property for AlleKrav and cannot be null");
            }
            else
            {
                this.Periode = periode;
            }
            // to ensure "skjermet" is required (not null)
            if (skjermet == null)
            {
                throw new InvalidDataException("skjermet is a required property for AlleKrav and cannot be null");
            }
            else
            {
                this.Skjermet = skjermet;
            }
            this.Krav = krav;
        }
        
        /// <summary>
        /// Gets or Sets PartIdentifikator
        /// </summary>
        [DataMember(Name="partIdentifikator", EmitDefaultValue=false)]
        public string PartIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Periode
        /// </summary>
        [DataMember(Name="periode", EmitDefaultValue=false)]
        public Periode Periode { get; set; }

        /// <summary>
        /// Vanligvis en debettransaksjon i reskontro, som kjennetegnes av at den skal betales av en debitor. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c63129-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
        /// </summary>
        /// <value>Vanligvis en debettransaksjon i reskontro, som kjennetegnes av at den skal betales av en debitor. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c63129-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)</value>
        [DataMember(Name="krav", EmitDefaultValue=false)]
        public List<Krav> Krav { get; set; }

        /// <summary>
        /// Gets or Sets Skjermet
        /// </summary>
        [DataMember(Name="skjermet", EmitDefaultValue=false)]
        public bool? Skjermet { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlleKrav {\n");
            sb.Append("  PartIdentifikator: ").Append(PartIdentifikator).Append("\n");
            sb.Append("  Periode: ").Append(Periode).Append("\n");
            sb.Append("  Krav: ").Append(Krav).Append("\n");
            sb.Append("  Skjermet: ").Append(Skjermet).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlleKrav);
        }

        /// <summary>
        /// Returns true if AlleKrav instances are equal
        /// </summary>
        /// <param name="input">Instance of AlleKrav to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlleKrav input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PartIdentifikator == input.PartIdentifikator ||
                    (this.PartIdentifikator != null &&
                    this.PartIdentifikator.Equals(input.PartIdentifikator))
                ) && 
                (
                    this.Periode == input.Periode ||
                    (this.Periode != null &&
                    this.Periode.Equals(input.Periode))
                ) && 
                (
                    this.Krav == input.Krav ||
                    this.Krav != null &&
                    input.Krav != null &&
                    this.Krav.SequenceEqual(input.Krav)
                ) && 
                (
                    this.Skjermet == input.Skjermet ||
                    (this.Skjermet != null &&
                    this.Skjermet.Equals(input.Skjermet))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PartIdentifikator != null)
                    hashCode = hashCode * 59 + this.PartIdentifikator.GetHashCode();
                if (this.Periode != null)
                    hashCode = hashCode * 59 + this.Periode.GetHashCode();
                if (this.Krav != null)
                    hashCode = hashCode * 59 + this.Krav.GetHashCode();
                if (this.Skjermet != null)
                    hashCode = hashCode * 59 + this.Skjermet.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
