/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// oversikt over gjeld, tilgodebeløp og betalinger mellom deg og Skatteetaten
    /// </summary>
    [DataContract]
        public partial class AlleKrav
    {
        /// <summary>
        /// Gets or Sets PartIdentifikator
        /// </summary>
        [DataMember(Name="partIdentifikator", EmitDefaultValue=false)]
        public string PartIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Periode
        /// </summary>
        [DataMember(Name="periode", EmitDefaultValue=false)]
        public Periode Periode { get; set; }

        /// <summary>
        /// Vanligvis en debettransaksjon i reskontro, som kjennetegnes av at den skal betales av en debitor. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c63129-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
        /// </summary>
        /// <value>Vanligvis en debettransaksjon i reskontro, som kjennetegnes av at den skal betales av en debitor. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c63129-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)</value>
        [DataMember(Name="krav", EmitDefaultValue=false)]
        public List<Krav> Krav { get; set; }

        /// <summary>
        /// Gets or Sets Skjermet
        /// </summary>
        [DataMember(Name="skjermet", EmitDefaultValue=false)]
        public bool? Skjermet { get; set; }

    }
}
