/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Betalingsinformasjon
    /// </summary>
    [DataContract]
        public partial class Betalingsinformasjon
    {
        /// <summary>
        /// Gets or Sets Kidnummer
        /// </summary>
        [DataMember(Name="kidnummer", EmitDefaultValue=false)]
        public string Kidnummer { get; set; }

        /// <summary>
        /// Gets or Sets MeldingSendtTilMottaker
        /// </summary>
        [DataMember(Name="meldingSendtTilMottaker", EmitDefaultValue=false)]
        public string MeldingSendtTilMottaker { get; set; }

        /// <summary>
        /// Gets or Sets Konto
        /// </summary>
        [DataMember(Name="konto", EmitDefaultValue=false)]
        public Bankkonto Konto { get; set; }

        /// <summary>
        /// Gets or Sets SjekkSendtTil
        /// </summary>
        [DataMember(Name="sjekkSendtTil", EmitDefaultValue=false)]
        public Mottaker SjekkSendtTil { get; set; }

        /// <summary>
        /// Gets or Sets UtbetalingskortSendtTil
        /// </summary>
        [DataMember(Name="utbetalingskortSendtTil", EmitDefaultValue=false)]
        public Mottaker UtbetalingskortSendtTil { get; set; }

        /// <summary>
        /// Gets or Sets Valutakode
        /// </summary>
        [DataMember(Name="valutakode", EmitDefaultValue=false)]
        public string Valutakode { get; set; }

    }
}
