/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// kravet som blir dekket i motregningen; beskrivelse av dekket krav slik at det ser ut i disponeringsbrev; dekket krav her er ofte referert som motkrav i fagdomene.
    /// </summary>
    [DataContract]
        public partial class DekketKrav
    {   
        /// <summary>
        /// Gets or Sets MotregnetBeloep
        /// </summary>
        [DataMember(Name="motregnetBeloep", EmitDefaultValue=false)]
        public double? MotregnetBeloep { get; set; }

        /// <summary>
        /// Gets or Sets DekketKravBeskrivelse
        /// </summary>
        [DataMember(Name="dekketKravBeskrivelse", EmitDefaultValue=false)]
        public MultiSpraakTekst DekketKravBeskrivelse { get; set; }

        /// <summary>
        /// Gets or Sets Innkrevingsmyndighet
        /// </summary>
        [DataMember(Name="innkrevingsmyndighet", EmitDefaultValue=false)]
        public MultiSpraakTekst Innkrevingsmyndighet { get; set; }

        /// <summary>
        /// Gets or Sets Forfallsdato
        /// </summary>
        [DataMember(Name="forfallsdato", EmitDefaultValue=false)]
        public DateTime? Forfallsdato { get; set; }

        /// <summary>
        /// Gets or Sets Kreditorsnavn
        /// </summary>
        [DataMember(Name="kreditorsnavn", EmitDefaultValue=false)]
        public MultiSpraakTekst Kreditorsnavn { get; set; }

        /// <summary>
        /// Gets or Sets Forsinkelsesrenter
        /// </summary>
        [DataMember(Name="forsinkelsesrenter", EmitDefaultValue=false)]
        public double? Forsinkelsesrenter { get; set; }
    }
}
