/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Fastsettingsmaate
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum Fastsettingsmaate
    {
        /// <summary>
        /// Enum Blank for value: blank
        /// </summary>
        [EnumMember(Value = "blank")]
        Blank = 1,
        /// <summary>
        /// Enum Egenfastsatt for value: egenfastsatt
        /// </summary>
        [EnumMember(Value = "egenfastsatt")]
        Egenfastsatt = 2,
        /// <summary>
        /// Enum Myndighetsfastsatt for value: myndighetsfastsatt
        /// </summary>
        [EnumMember(Value = "myndighetsfastsatt")]
        Myndighetsfastsatt = 3    }
}
