/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Feilstruktur for alle feilmeldinger.
    /// </summary>
    [DataContract]
        public partial class Feil 
    {
        /// <summary>
        /// Feilkode, for maskinell håndtering
        /// </summary>
        /// <value>Feilkode, for maskinell håndtering</value>
        [DataMember(Name="kode", EmitDefaultValue=false)]
        public string Kode { get; set; }

        /// <summary>
        /// Beskrivelse av feilen som har oppstått
        /// </summary>
        /// <value>Beskrivelse av feilen som har oppstått</value>
        [DataMember(Name="melding", EmitDefaultValue=false)]
        public string Melding { get; set; }

        /// <summary>
        /// Korrelasjonsid
        /// </summary>
        /// <value>Korrelasjonsid</value>
        [DataMember(Name="korrelasjonsid", EmitDefaultValue=false)]
        public string Korrelasjonsid { get; set; }
    }
}
