/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// GrunnlagForUtbetaling
    /// </summary>
    [DataContract]
        public partial class GrunnlagForUtbetaling
    {
        /// <summary>
        /// Gets or Sets KreditKrav
        /// </summary>
        [DataMember(Name="kreditKrav", EmitDefaultValue=false)]
        public List<KreditKrav> KreditKrav { get; set; }

        /// <summary>
        /// Gets or Sets TilbakebetalingAv
        /// </summary>
        [DataMember(Name="tilbakebetalingAv", EmitDefaultValue=false)]
        public List<InnbetalingPlassertMotUtbetaling> TilbakebetalingAv { get; set; }
    }
}
