/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// samling av alle tilgode beløp og innbetalinger som er brukt i motregningen
    /// </summary>
    [DataContract]
        public partial class HovedKrav
    {
        /// <summary>
        /// Gets or Sets InnbetalingBruktImotregning
        /// </summary>
        [DataMember(Name="innbetalingBruktImotregning", EmitDefaultValue=false)]
        public List<InnbetalingBruktIMotregning> InnbetalingBruktImotregning { get; set; }

        /// <summary>
        /// Gets or Sets KreditkravBruktIMotregning
        /// </summary>
        [DataMember(Name="kreditkravBruktIMotregning", EmitDefaultValue=false)]
        public List<KreditkravBruktIMotregning> KreditkravBruktIMotregning { get; set; }

    }
}
