/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// viser detaljer av hvilken innbetaling er plassert mot krav
    /// </summary>
    [DataContract]
        public partial class InnbetalingPlassertMotUtbetaling :  IEquatable<InnbetalingPlassertMotUtbetaling>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InnbetalingPlassertMotUtbetaling" /> class.
        /// </summary>
        /// <param name="innbetalingsIdentifikator">innbetalingsIdentifikator (required).</param>
        /// <param name="innbetalingstype">innbetalingstype (required).</param>
        /// <param name="innbetalingsdato">innbetalingsdato (required).</param>
        /// <param name="innbetaltBeloep">innbetaltBeloep (required).</param>
        /// <param name="innbetaltFra">innbetaltFra.</param>
        /// <param name="utbetaltBeloep">utbetaltBeloep.</param>
        public InnbetalingPlassertMotUtbetaling(string innbetalingsIdentifikator = default(string), string innbetalingstype = default(string), DateTime? innbetalingsdato = default(DateTime?), double? innbetaltBeloep = default(double?), Betalingsinformasjon innbetaltFra = default(Betalingsinformasjon), double? utbetaltBeloep = default(double?))
        {
            // to ensure "innbetalingsIdentifikator" is required (not null)
            if (innbetalingsIdentifikator == null)
            {
                throw new InvalidDataException("innbetalingsIdentifikator is a required property for InnbetalingPlassertMotUtbetaling and cannot be null");
            }
            else
            {
                this.InnbetalingsIdentifikator = innbetalingsIdentifikator;
            }
            // to ensure "innbetalingstype" is required (not null)
            if (innbetalingstype == null)
            {
                throw new InvalidDataException("innbetalingstype is a required property for InnbetalingPlassertMotUtbetaling and cannot be null");
            }
            else
            {
                this.Innbetalingstype = innbetalingstype;
            }
            // to ensure "innbetalingsdato" is required (not null)
            if (innbetalingsdato == null)
            {
                throw new InvalidDataException("innbetalingsdato is a required property for InnbetalingPlassertMotUtbetaling and cannot be null");
            }
            else
            {
                this.Innbetalingsdato = innbetalingsdato;
            }
            // to ensure "innbetaltBeloep" is required (not null)
            if (innbetaltBeloep == null)
            {
                throw new InvalidDataException("innbetaltBeloep is a required property for InnbetalingPlassertMotUtbetaling and cannot be null");
            }
            else
            {
                this.InnbetaltBeloep = innbetaltBeloep;
            }
            this.InnbetaltFra = innbetaltFra;
            this.UtbetaltBeloep = utbetaltBeloep;
        }
        
        /// <summary>
        /// Gets or Sets InnbetalingsIdentifikator
        /// </summary>
        [DataMember(Name="innbetalingsIdentifikator", EmitDefaultValue=false)]
        public string InnbetalingsIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Innbetalingstype
        /// </summary>
        [DataMember(Name="innbetalingstype", EmitDefaultValue=false)]
        public string Innbetalingstype { get; set; }

        /// <summary>
        /// Gets or Sets Innbetalingsdato
        /// </summary>
        [DataMember(Name="innbetalingsdato", EmitDefaultValue=false)]
        public DateTime? Innbetalingsdato { get; set; }

        /// <summary>
        /// Gets or Sets InnbetaltBeloep
        /// </summary>
        [DataMember(Name="innbetaltBeloep", EmitDefaultValue=false)]
        public double? InnbetaltBeloep { get; set; }

        /// <summary>
        /// Gets or Sets InnbetaltFra
        /// </summary>
        [DataMember(Name="innbetaltFra", EmitDefaultValue=false)]
        public Betalingsinformasjon InnbetaltFra { get; set; }

        /// <summary>
        /// Gets or Sets UtbetaltBeloep
        /// </summary>
        [DataMember(Name="utbetaltBeloep", EmitDefaultValue=false)]
        public double? UtbetaltBeloep { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InnbetalingPlassertMotUtbetaling {\n");
            sb.Append("  InnbetalingsIdentifikator: ").Append(InnbetalingsIdentifikator).Append("\n");
            sb.Append("  Innbetalingstype: ").Append(Innbetalingstype).Append("\n");
            sb.Append("  Innbetalingsdato: ").Append(Innbetalingsdato).Append("\n");
            sb.Append("  InnbetaltBeloep: ").Append(InnbetaltBeloep).Append("\n");
            sb.Append("  InnbetaltFra: ").Append(InnbetaltFra).Append("\n");
            sb.Append("  UtbetaltBeloep: ").Append(UtbetaltBeloep).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InnbetalingPlassertMotUtbetaling);
        }

        /// <summary>
        /// Returns true if InnbetalingPlassertMotUtbetaling instances are equal
        /// </summary>
        /// <param name="input">Instance of InnbetalingPlassertMotUtbetaling to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InnbetalingPlassertMotUtbetaling input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InnbetalingsIdentifikator == input.InnbetalingsIdentifikator ||
                    (this.InnbetalingsIdentifikator != null &&
                    this.InnbetalingsIdentifikator.Equals(input.InnbetalingsIdentifikator))
                ) && 
                (
                    this.Innbetalingstype == input.Innbetalingstype ||
                    (this.Innbetalingstype != null &&
                    this.Innbetalingstype.Equals(input.Innbetalingstype))
                ) && 
                (
                    this.Innbetalingsdato == input.Innbetalingsdato ||
                    (this.Innbetalingsdato != null &&
                    this.Innbetalingsdato.Equals(input.Innbetalingsdato))
                ) && 
                (
                    this.InnbetaltBeloep == input.InnbetaltBeloep ||
                    (this.InnbetaltBeloep != null &&
                    this.InnbetaltBeloep.Equals(input.InnbetaltBeloep))
                ) && 
                (
                    this.InnbetaltFra == input.InnbetaltFra ||
                    (this.InnbetaltFra != null &&
                    this.InnbetaltFra.Equals(input.InnbetaltFra))
                ) && 
                (
                    this.UtbetaltBeloep == input.UtbetaltBeloep ||
                    (this.UtbetaltBeloep != null &&
                    this.UtbetaltBeloep.Equals(input.UtbetaltBeloep))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InnbetalingsIdentifikator != null)
                    hashCode = hashCode * 59 + this.InnbetalingsIdentifikator.GetHashCode();
                if (this.Innbetalingstype != null)
                    hashCode = hashCode * 59 + this.Innbetalingstype.GetHashCode();
                if (this.Innbetalingsdato != null)
                    hashCode = hashCode * 59 + this.Innbetalingsdato.GetHashCode();
                if (this.InnbetaltBeloep != null)
                    hashCode = hashCode * 59 + this.InnbetaltBeloep.GetHashCode();
                if (this.InnbetaltFra != null)
                    hashCode = hashCode * 59 + this.InnbetaltFra.GetHashCode();
                if (this.UtbetaltBeloep != null)
                    hashCode = hashCode * 59 + this.UtbetaltBeloep.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
