/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// viser alle innbetalinger for en valgt periode. Du får oversikt over innbetalinger som er gjort, og hvilke krav som har blitt dekket.
    /// </summary>
    [DataContract]
        public partial class Innbetalinger
    {
        /// <summary>
        /// Gets or Sets PartIdentifikator
        /// </summary>
        [DataMember(Name="partIdentifikator", EmitDefaultValue=false)]
        public string PartIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Periode
        /// </summary>
        [DataMember(Name="periode", EmitDefaultValue=false)]
        public Periode Periode { get; set; }

        /// <summary>
        /// overføring av penger til kreditor eller kreditors representant. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c6311e-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
        /// </summary>
        /// <value>overføring av penger til kreditor eller kreditors representant. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c6311e-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)</value>
        [DataMember(Name="innbetaling", EmitDefaultValue=false)]
        public List<Innbetaling> Innbetaling { get; set; }

        /// <summary>
        /// Gets or Sets Skjermet
        /// </summary>
        [DataMember(Name="skjermet", EmitDefaultValue=false)]
        public bool? Skjermet { get; set; }
    }
}
