/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Text;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
namespace IO.Swagger.Model
{
    /// <summary>
    /// overføring av penger til kreditor eller kreditors representant. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c6311e-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
    /// </summary>
    [DataContract]
        public partial class Innbetaling
    {
        /// <summary>
        /// Gets or Sets PartIdentifikator
        /// </summary>
        [DataMember(Name="partIdentifikator", EmitDefaultValue=false)]
        public string PartIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Innbetalingsidentifikator
        /// </summary>
        [DataMember(Name="innbetalingsidentifikator", EmitDefaultValue=false)]
        public string Innbetalingsidentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Innbetalingsdato
        /// </summary>
        [DataMember(Name="innbetalingsdato", EmitDefaultValue=false)]
        public DateTime? Innbetalingsdato { get; set; }

        /// <summary>
        /// Gets or Sets InnbetaltBeloep
        /// </summary>
        [DataMember(Name="innbetaltBeloep", EmitDefaultValue=false)]
        public double? InnbetaltBeloep { get; set; }

        /// <summary>
        /// innbetaling som er plassert mot et gitt krav
        /// </summary>
        /// <value>innbetaling som er plassert mot et gitt krav</value>
        [DataMember(Name="plassertKrav", EmitDefaultValue=false)]
        public List<KravPlassertMotInnbetaling> PlassertKrav { get; set; }

        /// <summary>
        /// Gets or Sets UplassertBeloep
        /// </summary>
        [DataMember(Name="uplassertBeloep", EmitDefaultValue=false)]
        public double? UplassertBeloep { get; set; }

        /// <summary>
        /// Gets or Sets MottakersKontonummer
        /// </summary>
        [DataMember(Name="mottakersKontonummer", EmitDefaultValue=false)]
        public Bankkonto MottakersKontonummer { get; set; }

        /// <summary>
        /// Gets or Sets InnbetaltFra
        /// </summary>
        [DataMember(Name="innbetaltFra", EmitDefaultValue=false)]
        public Betalingsinformasjon InnbetaltFra { get; set; }

        /// <summary>
        /// Gets or Sets Innbetalingstype
        /// </summary>
        [DataMember(Name="innbetalingstype", EmitDefaultValue=false)]
        public string Innbetalingstype { get; set; }

        /// <summary>
        /// Gets or Sets PlassertUtbetaling
        /// </summary>
        [DataMember(Name="plassertUtbetaling", EmitDefaultValue=false)]
        public List<UtbetalingPlassertMotInnbetaling> PlassertUtbetaling { get; set; }

        /// <summary>
        /// Gets or Sets MotregningAvInnbetaling
        /// </summary>
        [DataMember(Name="motregningAvInnbetaling", EmitDefaultValue=false)]
        public MotregningAvInnbetaling MotregningAvInnbetaling { get; set; }

    }
}
