/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// angivelse av beløp fra kreditpost som går til dekning av debetpost (&lt;a href&#x3D;&#x27;http://begrepskatalog/begrep/35c63137-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
    /// </summary>
    [DataContract]
        public partial class KravPlassertMotInnbetaling
    {
        /// <summary>
        /// Gets or Sets KravforfallIdentifikator
        /// </summary>
        [DataMember(Name="kravforfallIdentifikator", EmitDefaultValue=false)]
        public string KravforfallIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets PlassertBeloep
        /// </summary>
        [DataMember(Name="plassertBeloep", EmitDefaultValue=false)]
        public double? PlassertBeloep { get; set; }

        /// <summary>
        /// Gets or Sets PlassertDato
        /// </summary>
        [DataMember(Name="plassertDato", EmitDefaultValue=false)]
        public DateTime? PlassertDato { get; set; }

        /// <summary>
        /// Gets or Sets Kravbeskrivelse
        /// </summary>
        [DataMember(Name="kravbeskrivelse", EmitDefaultValue=false)]
        public MultiSpraakTekst Kravbeskrivelse { get; set; }

        /// <summary>
        /// Gets or Sets Kravforfallsdato
        /// </summary>
        [DataMember(Name="kravforfallsdato", EmitDefaultValue=false)]
        public DateTime? Kravforfallsdato { get; set; }

        /// <summary>
        /// Gets or Sets OpprinneligKravforfallsbeloep
        /// </summary>
        [DataMember(Name="opprinneligKravforfallsbeloep", EmitDefaultValue=false)]
        public double? OpprinneligKravforfallsbeloep { get; set; }

        /// <summary>
        /// Gets or Sets GjenstaaendeKravforfallsbeloep
        /// </summary>
        [DataMember(Name="gjenstaaendeKravforfallsbeloep", EmitDefaultValue=false)]
        public double? GjenstaaendeKravforfallsbeloep { get; set; }
    }
}
