/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Krav (pengekrav) er forpliktelse til å betale eller rett til å motta en bestemt sum penger. (&lt;a href&#x3D;&#x27;http://data.skatteetaten.no/begrep/35c63129-86e6-11e6-a97e-ba992a0501a6&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
    /// </summary>
    [DataContract]
        public partial class Krav
    {
        /// <summary>
        /// Gets or Sets PartIdentifikator
        /// </summary>
        [DataMember(Name="partIdentifikator", EmitDefaultValue=false)]
        public string PartIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Kravidentifikator
        /// </summary>
        [DataMember(Name="kravidentifikator", EmitDefaultValue=false)]
        public string Kravidentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Kravtype
        /// </summary>
        [DataMember(Name="kravtype", EmitDefaultValue=false)]
        public string Kravtype { get; set; }

        /// <summary>
        /// Gets or Sets OpprinneligBeloep
        /// </summary>
        [DataMember(Name="opprinneligBeloep", EmitDefaultValue=false)]
        public double? OpprinneligBeloep { get; set; }

        /// <summary>
        /// Gets or Sets GjenstaaendeBeloep
        /// </summary>
        [DataMember(Name="gjenstaaendeBeloep", EmitDefaultValue=false)]
        public double? GjenstaaendeBeloep { get; set; }

        /// <summary>
        /// Gets or Sets StipulerteRenter
        /// </summary>
        [DataMember(Name="stipulerteRenter", EmitDefaultValue=false)]
        public double? StipulerteRenter { get; set; }

        /// <summary>
        /// frist for å betale krav. En krav kan ha flere forfall(frister), med ulike beløp i vise tilfeller  (f. eks. forskuddsskatt).
        /// </summary>
        /// <value>frist for å betale krav. En krav kan ha flere forfall(frister), med ulike beløp i vise tilfeller  (f. eks. forskuddsskatt).</value>
        [DataMember(Name="kravforfall", EmitDefaultValue=false)]
        public List<Kravforfall> Kravforfall { get; set; }

        /// <summary>
        /// Gets or Sets Kravbeskrivelse
        /// </summary>
        [DataMember(Name="kravbeskrivelse", EmitDefaultValue=false)]
        public MultiSpraakTekst Kravbeskrivelse { get; set; }

        /// <summary>
        /// Gets or Sets Kravperiode
        /// </summary>
        [DataMember(Name="kravperiode", EmitDefaultValue=false)]
        public Kravperiode Kravperiode { get; set; }

        /// <summary>
        /// Gets or Sets OpprettelsesdatoForKrav
        /// </summary>
        [DataMember(Name="opprettelsesdatoForKrav", EmitDefaultValue=false)]
        public DateTime? OpprettelsesdatoForKrav { get; set; }

        /// <summary>
        /// Gets or Sets Kravgruppe
        /// </summary>
        [DataMember(Name="kravgruppe", EmitDefaultValue=false)]
        public string Kravgruppe { get; set; }

        /// <summary>
        /// Gets or Sets HovedstolKravidentifikator
        /// </summary>
        [DataMember(Name="hovedstolKravidentifikator", EmitDefaultValue=false)]
        public string HovedstolKravidentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Fastsettingsmaate
        /// </summary>
        [DataMember(Name="fastsettingsmaate", EmitDefaultValue=false)]
        public Fastsettingsmaate Fastsettingsmaate { get; set; }

        /// <summary>
        /// Gets or Sets MotregningAvKreditkrav
        /// </summary>
        [DataMember(Name="motregningAvKreditkrav", EmitDefaultValue=false)]
        public MotregningAvKreditkrav MotregningAvKreditkrav { get; set; }
    }
}
