/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// forfall, forfallsdag eller forfallstid er det tidspunkt da en fordring kan kreves oppfylt (skal betales). Forfallsdato for skatte- og avgiftskrav er lovbestemt. (&lt;a href&#x3D;&#x27;http://begrepskatalog/begrep/978e3c52-5f59-11e9-abae-005056821322&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
    /// </summary>
    [DataContract]
        public partial class Kravforfall
    {
       
        /// <summary>
        /// Gets or Sets KravforfallsIdentifikator
        /// </summary>
        [DataMember(Name="kravforfallsIdentifikator", EmitDefaultValue=false)]
        public string KravforfallsIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Forfallsdato
        /// </summary>
        [DataMember(Name="forfallsdato", EmitDefaultValue=false)]
        public DateTime? Forfallsdato { get; set; }

        /// <summary>
        /// Gets or Sets OpprinneligBeloep
        /// </summary>
        [DataMember(Name="opprinneligBeloep", EmitDefaultValue=false)]
        public double? OpprinneligBeloep { get; set; }

        /// <summary>
        /// innbetaling som er plassert mot et gitt krav med en gitt betalingsfrist
        /// </summary>
        /// <value>innbetaling som er plassert mot et gitt krav med en gitt betalingsfrist</value>
        [DataMember(Name="plassertInnbetaling", EmitDefaultValue=false)]
        public List<InnbetalingPlassertMotKrav> PlassertInnbetaling { get; set; }

        /// <summary>
        /// motkrav som ble plassert mot en krav i en oppgjøring. (&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begrep/e05d0c26-8f88-11ea-a408-005056828ed3&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
        /// </summary>
        /// <value>motkrav som ble plassert mot en krav i en oppgjøring. (&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begrep/e05d0c26-8f88-11ea-a408-005056828ed3&#x27;&gt;Begrepsreferanse&lt;/a&gt;)</value>
        [DataMember(Name="plassertMotkrav", EmitDefaultValue=false)]
        public List<KravPlassertMotKrav> PlassertMotkrav { get; set; }

        /// <summary>
        /// Gets or Sets GjenstaaendeBeloep
        /// </summary>
        [DataMember(Name="gjenstaaendeBeloep", EmitDefaultValue=false)]
        public double? GjenstaaendeBeloep { get; set; }

        /// <summary>
        /// Gets or Sets Betalingsinformasjon
        /// </summary>
        [DataMember(Name="betalingsinformasjon", EmitDefaultValue=false)]
        public Betalingsinformasjon Betalingsinformasjon { get; set; }

        /// <summary>
        /// Gets or Sets PlassertUtbetaling
        /// </summary>
        [DataMember(Name="plassertUtbetaling", EmitDefaultValue=false)]
        public List<UtbetalingPlassertMotKrav> PlassertUtbetaling { get; set; }
    }
}
