/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Mottaker
    /// </summary>
    [DataContract]
        public partial class Mottaker
    {
        /// <summary>
        /// Gets or Sets MottakersNavn
        /// </summary>
        [DataMember(Name="mottakersNavn", EmitDefaultValue=false)]
        public string MottakersNavn { get; set; }

        /// <summary>
        /// Gets or Sets MottakersAddresse
        /// </summary>
        [DataMember(Name="mottakersAddresse", EmitDefaultValue=false)]
        public AdresseFrittFormat MottakersAddresse { get; set; }
    }
}
