/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// tekster som representerer samme mening på flere språk (&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begrep/20b2e242-9fe1-11e5-a9f8-e4115b280940&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
    /// </summary>
    [DataContract]
        public partial class MultiSpraakTekst
    {
        /// <summary>
        /// (&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begrep/20b2e244-9fe1-11e5-a9f8-e4115b280940&#x27;&gt;Begrepsreferanse&lt;/a&gt;)
        /// </summary>
        /// <value>(&lt;a href&#x3D;&#x27;https://data.skatteetaten.no/begrep/20b2e244-9fe1-11e5-a9f8-e4115b280940&#x27;&gt;Begrepsreferanse&lt;/a&gt;)</value>
        [DataMember(Name="spraakTekst", EmitDefaultValue=false)]
        public List<SpraakTekst> SpraakTekst { get; set; }
    }
}
