/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// overføring av penger fra kreditor eller kreditors representant.
    /// </summary>
    [DataContract]
        public partial class Utbetaling :  IEquatable<Utbetaling>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Utbetaling" /> class.
        /// </summary>
        /// <param name="partIdentifikator">partIdentifikator (required).</param>
        /// <param name="utbetalingsidentifikator">utbetalingsidentifikator (required).</param>
        /// <param name="utbetaltdato">utbetaltdato (required).</param>
        /// <param name="utbetaltBeloep">utbetaltBeloep (required).</param>
        /// <param name="betaltTil">betaltTil (required).</param>
        /// <param name="grunnlagForUtbetaling">grunnlagForUtbetaling (required).</param>
        /// <param name="utbetalingstatus">utbetalingstatus.</param>
        public Utbetaling(string partIdentifikator = default(string), string utbetalingsidentifikator = default(string), DateTime? utbetaltdato = default(DateTime?), double? utbetaltBeloep = default(double?), Betalingsinformasjon betaltTil = default(Betalingsinformasjon), GrunnlagForUtbetaling grunnlagForUtbetaling = default(GrunnlagForUtbetaling), Utbetalingstatus utbetalingstatus = default(Utbetalingstatus))
        {
            // to ensure "partIdentifikator" is required (not null)
            if (partIdentifikator == null)
            {
                throw new InvalidDataException("partIdentifikator is a required property for Utbetaling and cannot be null");
            }
            else
            {
                this.PartIdentifikator = partIdentifikator;
            }
            // to ensure "utbetalingsidentifikator" is required (not null)
            if (utbetalingsidentifikator == null)
            {
                throw new InvalidDataException("utbetalingsidentifikator is a required property for Utbetaling and cannot be null");
            }
            else
            {
                this.Utbetalingsidentifikator = utbetalingsidentifikator;
            }
            // to ensure "utbetaltdato" is required (not null)
            if (utbetaltdato == null)
            {
                throw new InvalidDataException("utbetaltdato is a required property for Utbetaling and cannot be null");
            }
            else
            {
                this.Utbetaltdato = utbetaltdato;
            }
            // to ensure "utbetaltBeloep" is required (not null)
            if (utbetaltBeloep == null)
            {
                throw new InvalidDataException("utbetaltBeloep is a required property for Utbetaling and cannot be null");
            }
            else
            {
                this.UtbetaltBeloep = utbetaltBeloep;
            }
            // to ensure "betaltTil" is required (not null)
            if (betaltTil == null)
            {
                throw new InvalidDataException("betaltTil is a required property for Utbetaling and cannot be null");
            }
            else
            {
                this.BetaltTil = betaltTil;
            }
            // to ensure "grunnlagForUtbetaling" is required (not null)
            if (grunnlagForUtbetaling == null)
            {
                throw new InvalidDataException("grunnlagForUtbetaling is a required property for Utbetaling and cannot be null");
            }
            else
            {
                this.GrunnlagForUtbetaling = grunnlagForUtbetaling;
            }
            this.Utbetalingstatus = utbetalingstatus;
        }
        
        /// <summary>
        /// Gets or Sets PartIdentifikator
        /// </summary>
        [DataMember(Name="partIdentifikator", EmitDefaultValue=false)]
        public string PartIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Utbetalingsidentifikator
        /// </summary>
        [DataMember(Name="utbetalingsidentifikator", EmitDefaultValue=false)]
        public string Utbetalingsidentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Utbetaltdato
        /// </summary>
        [DataMember(Name="utbetaltdato", EmitDefaultValue=false)]
        public DateTime? Utbetaltdato { get; set; }

        /// <summary>
        /// Gets or Sets UtbetaltBeloep
        /// </summary>
        [DataMember(Name="utbetaltBeloep", EmitDefaultValue=false)]
        public double? UtbetaltBeloep { get; set; }

        /// <summary>
        /// Gets or Sets BetaltTil
        /// </summary>
        [DataMember(Name="betaltTil", EmitDefaultValue=false)]
        public Betalingsinformasjon BetaltTil { get; set; }

        /// <summary>
        /// Gets or Sets GrunnlagForUtbetaling
        /// </summary>
        [DataMember(Name="grunnlagForUtbetaling", EmitDefaultValue=false)]
        public GrunnlagForUtbetaling GrunnlagForUtbetaling { get; set; }

        /// <summary>
        /// Gets or Sets Utbetalingstatus
        /// </summary>
        [DataMember(Name="utbetalingstatus", EmitDefaultValue=false)]
        public Utbetalingstatus Utbetalingstatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Utbetaling {\n");
            sb.Append("  PartIdentifikator: ").Append(PartIdentifikator).Append("\n");
            sb.Append("  Utbetalingsidentifikator: ").Append(Utbetalingsidentifikator).Append("\n");
            sb.Append("  Utbetaltdato: ").Append(Utbetaltdato).Append("\n");
            sb.Append("  UtbetaltBeloep: ").Append(UtbetaltBeloep).Append("\n");
            sb.Append("  BetaltTil: ").Append(BetaltTil).Append("\n");
            sb.Append("  GrunnlagForUtbetaling: ").Append(GrunnlagForUtbetaling).Append("\n");
            sb.Append("  Utbetalingstatus: ").Append(Utbetalingstatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Utbetaling);
        }

        /// <summary>
        /// Returns true if Utbetaling instances are equal
        /// </summary>
        /// <param name="input">Instance of Utbetaling to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Utbetaling input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PartIdentifikator == input.PartIdentifikator ||
                    (this.PartIdentifikator != null &&
                    this.PartIdentifikator.Equals(input.PartIdentifikator))
                ) && 
                (
                    this.Utbetalingsidentifikator == input.Utbetalingsidentifikator ||
                    (this.Utbetalingsidentifikator != null &&
                    this.Utbetalingsidentifikator.Equals(input.Utbetalingsidentifikator))
                ) && 
                (
                    this.Utbetaltdato == input.Utbetaltdato ||
                    (this.Utbetaltdato != null &&
                    this.Utbetaltdato.Equals(input.Utbetaltdato))
                ) && 
                (
                    this.UtbetaltBeloep == input.UtbetaltBeloep ||
                    (this.UtbetaltBeloep != null &&
                    this.UtbetaltBeloep.Equals(input.UtbetaltBeloep))
                ) && 
                (
                    this.BetaltTil == input.BetaltTil ||
                    (this.BetaltTil != null &&
                    this.BetaltTil.Equals(input.BetaltTil))
                ) && 
                (
                    this.GrunnlagForUtbetaling == input.GrunnlagForUtbetaling ||
                    (this.GrunnlagForUtbetaling != null &&
                    this.GrunnlagForUtbetaling.Equals(input.GrunnlagForUtbetaling))
                ) && 
                (
                    this.Utbetalingstatus == input.Utbetalingstatus ||
                    (this.Utbetalingstatus != null &&
                    this.Utbetalingstatus.Equals(input.Utbetalingstatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PartIdentifikator != null)
                    hashCode = hashCode * 59 + this.PartIdentifikator.GetHashCode();
                if (this.Utbetalingsidentifikator != null)
                    hashCode = hashCode * 59 + this.Utbetalingsidentifikator.GetHashCode();
                if (this.Utbetaltdato != null)
                    hashCode = hashCode * 59 + this.Utbetaltdato.GetHashCode();
                if (this.UtbetaltBeloep != null)
                    hashCode = hashCode * 59 + this.UtbetaltBeloep.GetHashCode();
                if (this.BetaltTil != null)
                    hashCode = hashCode * 59 + this.BetaltTil.GetHashCode();
                if (this.GrunnlagForUtbetaling != null)
                    hashCode = hashCode * 59 + this.GrunnlagForUtbetaling.GetHashCode();
                if (this.Utbetalingstatus != null)
                    hashCode = hashCode * 59 + this.Utbetalingstatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
