/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// UtbetalingPlassertMotInnbetaling
    /// </summary>
    [DataContract]
        public partial class UtbetalingPlassertMotInnbetaling
    {
        /// <summary>
        /// Gets or Sets Utbetalingsidentifikator
        /// </summary>
        [DataMember(Name="utbetalingsidentifikator", EmitDefaultValue=false)]
        public string Utbetalingsidentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Utbetaltdato
        /// </summary>
        [DataMember(Name="utbetaltdato", EmitDefaultValue=false)]
        public DateTime? Utbetaltdato { get; set; }

        /// <summary>
        /// Gets or Sets UtbetaltBeloep
        /// </summary>
        [DataMember(Name="utbetaltBeloep", EmitDefaultValue=false)]
        public double? UtbetaltBeloep { get; set; }

        /// <summary>
        /// Gets or Sets BetaltTil
        /// </summary>
        [DataMember(Name="betaltTil", EmitDefaultValue=false)]
        public Betalingsinformasjon BetaltTil { get; set; }
    }
}
