/* 
 * Krav og betalinger API
 *
 * Tjeneste som tilbyr oversikt av krav, innbetalinger og utbetalinger tilhørende en part.
 *
 * OpenAPI spec version: 1.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
namespace IO.Swagger.Model
{
    /// <summary>
    /// oversikt over utbetalinger utført til en part
    /// </summary>
    [DataContract]
        public partial class Utbetalinger
    {
        /// <summary>
        /// Gets or Sets PartIdentifikator
        /// </summary>
        [DataMember(Name="partIdentifikator", EmitDefaultValue=false)]
        public string PartIdentifikator { get; set; }

        /// <summary>
        /// Gets or Sets Periode
        /// </summary>
        [DataMember(Name="periode", EmitDefaultValue=false)]
        public Periode Periode { get; set; }

        /// <summary>
        /// overføring av penger fra kreditor eller kreditors representant.
        /// </summary>
        /// <value>overføring av penger fra kreditor eller kreditors representant.</value>
        [DataMember(Name="utbetaling", EmitDefaultValue=false)]
        public List<Utbetaling> Utbetaling { get; set; }

        /// <summary>
        /// Gets or Sets Skjermet
        /// </summary>
        [DataMember(Name="skjermet", EmitDefaultValue=false)]
        public bool? Skjermet { get; set; }
    }
}
